export const BAGUIO_BARANGAYS = [
  "Abanao-Zandueta-Kayang-Chugum-Otek-Penzola (AZKCO)",
  "Alfonso Tabora",
  "Ambiong",
  "Andres Bonifacio",
  "Apugan-Loakan",
  "Atab District",
  "Bakakeng Central",
  "Bakakeng North",
  "Bal-Marc-Hacienda (Balacbac)",
  "Balsigan",
  "Bayan Park East",
  "Bayan Park Village",
  "Bayan Park West",
  "BGH Compound",
  "Brookside",
  "Brookspoint",
  "Cabinet Hill-Teacher's Camp",
  "Camdas Subdivision",
  "Camp 7",
  "Camp 8",
  "Camp Allen",
  "Campo Filipino",
  "City Camp Central",
  "City Camp Lagoon",
  "Country Club Village",
  "Cresencia Village",
  "Dagsian (Lower)",
  "Dagsian (Upper)",
  "Dizon Subdivision",
  "Dominican Hill-Mirador",
  "Doña Aurora",
  "Doña Edith Rizal",
  "Doña Herminia",
  "East Bayan Park",
  "East Modern site",
  "Engineers Hill",
  "Fairview Village",
  "Fort del Pilar",
  "Gabriela Silang",
  "General Emilio F. Aguinaldo",
  "General Luna (Lower)",
  "General Luna (Upper)",
  "Gibraltar",
  "Greenwater Village",
  "Guisad Central",
  "Guisad Sorong",
  "Harrison-Claudio Carantes",
  "Hillside",
  "Holy Ghost Extension",
  "Holy Ghost Proper",
  "Honeymoon-Holy Ghost",
  "Imelda Village",
  "Irisan",
  "Jose P. Laurel",
  "Kabayanihan",
  "Kagitingan",
  "Kayang Extension",
  "Kayang-Hilltop",
  "Kias",
  "Loakan Liwanag",
  "Loakan Proper",
  "Lopez Jaena",
  "Lualhati",
  "Lucnab",
  "Magsaysay Central",
  "Magsaysay Lower",
  "Magsaysay Upper",
  "Malcolm Square-Perfecto (MPS)",
  "Manuel A. Roxas",
  "Market Subdivision",
  "Middle Quezon Hill",
  "Middle Rock Quarry",
  "Military Cut-off",
  "Mines View Park",
  "Modern Site (East)",
  "Modern Site (West)",
  "MRR-Queen of Peace",
  "North Bayan Park",
  "North Central Aurora Hill",
  "North Sanctuary",
  "Outlook Drive",
  "Pacdal",
  "Padcal Village",
  "Palo Alto",
  "Phil-Am",
  "Pinget",
  "Pinsao Proper",
  "Pinsao Pilot Project",
  "Pucsusan",
  "Quezon Hill Proper",
  "Quezon Hill Upper",
  "Quirino Hill (Lower)",
  "Quirino Hill (Middle)",
  "Quirino Hill (Upper)",
  "Quirino-Magsaysay (Upper)",
  "Rizal Monument Area",
  "Rock Quarry (Lower)",
  "Rock Quarry (Middle)",
  "Rock Quarry (Upper)",
  "Saint Joseph Village",
  "Salud Mitra",
  "San Antonio Village",
  "San Luis Village",
  "San Roque Village",
  "San Vicente",
  "Santa Escolastica",
  "Santo Niño",
  "Santo Rosario",
  "Scout Barrio",
  "Session Road Area",
  "Slaughter House Area",
  "South Central Aurora Hill",
  "South Drive",
  "Sto. Niño Village",
  "Teodora Alonzo",
  "Trancoville",
  "Upper Dagsian",
  "Upper Gen. Luna",
  "Upper Magsaysay",
  "Upper Market Subdivision",
  "Upper Quezon Hill",
  "Upper Rock Quarry",
  "Victoria Village",
  "West Bayan Park",
  "West Modernsite"
].sort();
